[project]
name = "kkafio"
version = "2.0.0"
description = "Koikatsu Auto File I/O. Create backup, filter and convert kks cards, install/remove chara given a folder."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "certifi>=2026.2.25",
    "imagehash>=4.3.2",
    "packaging>=26.0",
    "patool>=3.0.0",
    "pillow>=12.2.0",
    "psutil>=6.0.0",
    "pyside6-essentials>=6.7.2",
    "pyside6-fluent-widgets>=1.6.5",
    "pysidesix-frameless-window>=0.4.3",
    "send2trash>=1.8.3",
]

[dependency-groups]
dev = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.5",
]

build = [
    "hatchling>=1.29.0",
    "pyinstaller>=6.19.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
