[project]
name = "kkafio"
version = "2.0.0"
description = "Koikatsu Auto File I/O. Create backup, filter and convert kks cards, install/remove chara given a folder."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "beautifulsoup4>=4.15.0",
    "certifi>=2026.2.25",
    "httpx>=0.28.1",
    "imagehash>=4.3.2",
    "kkloader>=0.1.20",
    "packaging>=26.0",
    "send2trash>=1.8.3",
    "teleget9527[fast]>=0.2.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

build = [
    "hatchling>=1.29.0",
    "pyinstaller>=6.19.0",
]

[tool.hatch.build.targets.wheel]
include = [
  "kkafio_cli.py",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-v --tb=short"
